version: '3.5'
services:
  imgpush:
    ports:
        - "5000:5000"
    build: .
    volumes:
      - /imgpush/app:/app
      - /imgpush/images:/images
      - /imgpush/cache:/cache
    healthcheck:
      test: ['CMD-SHELL', 'curl localhost:5000/liveness -s -f -o /dev/null || exit 1']
      interval: 30s
